project_name: "dotfiles"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "zed-preview --wait"
auto_open_browser: true
default_port: 6420
remote_operations: false
auto_commit: false
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: false
active_branch_days: 30
task_prefix: "task"
