theme = "gruvbox"

[editor]
cursorline = true
auto-save = true
bufferline = "multiple"
color-modes = true
true-color = true
gutters = ["diagnostics", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
# enable = true
wrap-at-text-width = true

[keys.normal]
D = ["extend_to_line_end", "delete_selection"]

[keys.normal.space]
v = ":write"
# y = "yank_to_clipboard"
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"

# [keys.select]
# y = "yank_to_clipboard"
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
