[tools]
rust = "latest"
uv = "latest"
node = "lts"
bun = "latest"
jj = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
helix = "latest"
"core:elixir" = "1.18.4-otp-27"

[settings]
idiomatic_version_file_enable_tools = ["[]"]
